# Generated by Django 5.1.7 on 2025-03-28 14:40

import contracts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_booking_status_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default=contracts.models.default_end_date),
        ),
        migrations.AddField(
            model_name='booking',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
