# Generated by Django 5.1.7 on 2025-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudreport',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
