# Generated by Django 5.1.7 on 2025-03-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fraudreport_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraudreport',
            old_name='reason',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fraudreport',
            old_name='reported_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
