# Generated by Django 5.1.7 on 2025-05-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_is_owner'),
        ('properties', '0012_rename_agent_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraudreport',
            old_name='title',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='fraudreport',
            name='reason',
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property'),
        ),
    ]
