# Generated by Django 5.1.7 on 2025-05-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_title_fraudreport_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycverification',
            old_name='rejection_reason',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='is_verified',
        ),
    ]
