# Generated by Django 5.1.7 on 2025-05-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_rejection_reason_kycverification_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
