# Generated by Django 5.1.7 on 2025-03-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='reported_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
