# Generated by Django 5.1.7 on 2025-03-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_expiry_date_property_is_rental_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_prices', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'months')},
            },
        ),
    ]
