# Generated by Django 5.1.7 on 2025-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
