# Generated by Django 5.1.7 on 2025-04-03 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_address_userprofile_phone_number_and_more'),
        ('properties', '0010_property_rental_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.userprofile'),
        ),
    ]
