# Generated by Django 5.1.7 on 2025-04-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agent',
            new_name='owner',
        ),
    ]
